# Generated by Django 4.2.2 on 2023-07-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='link',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
